/*
 * This file is generated by jOOQ.
*/
package geodata.db;


import geodata.db.tables.City;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = geodata.db.tables.City.CITY;
}
