/*
 * This file is generated by jOOQ.
*/
package geodata.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City implements Serializable {

    private static final long serialVersionUID = 756791648;

    private Long    id;
    private String  name;
    private Integer population;

    public City() {}

    public City(City value) {
        this.id = value.id;
        this.name = value.name;
        this.population = value.population;
    }

    public City(
        Long    id,
        String  name,
        Integer population
    ) {
        this.id = id;
        this.name = name;
        this.population = population;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPopulation() {
        return this.population;
    }

    public void setPopulation(Integer population) {
        this.population = population;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(population);

        sb.append(")");
        return sb.toString();
    }
}
